import { AppData } from '../api/types';

const heatmap = Array.from({ length: 84 }, (_, index) => {
  const pattern = [0, 1, 2, 3, 2, 1, 0];
  return pattern[index % pattern.length];
});

export const seedData: AppData = {
  user: {
    id: 'client-anna',
    name: 'Анна Карпова',
    initials: 'АК',
    phone: '+7 (999) 123-45-67',
    cardNumber: 'A-4710',
    roles: ['client', 'trainer', 'admin'],
  },

  membership: {
    id: 'member-4710',
    title: 'Годовой безлимит',
    status: 'active',
    expiresAt: '01 июня 2026',
    daysLeft: 73,
    progressPct: 68,
    freezesLeft: 2,
    poolVisitsLeft: 8,
    zones: [
      { label: 'Тренажёрный зал', available: true },
      { label: 'Групповые', available: true },
      { label: 'Бассейн', available: true },
      { label: 'Сауна', available: true },
    ],
  },

  classes: [
    {
      id: 'class-morning-stretch',
      date: '2026-04-20',
      time: '08:00',
      name: 'Утренний стретчинг',
      trainer: 'Мария К.',
      room: 'Зал №3',
      duration: '45 мин',
      spots: 6,
      total: 12,
      type: 'Йога',
      booked: false,
    },
    {
      id: 'class-functional',
      date: '2026-04-20',
      time: '10:00',
      name: 'Функциональная тренировка',
      trainer: 'Игорь В.',
      room: 'Зал №2',
      duration: '60 мин',
      spots: 2,
      total: 14,
      type: 'Групповые',
      booked: true,
    },
    {
      id: 'class-aqua',
      date: '2026-04-21',
      time: '12:30',
      name: 'Аквааэробика',
      trainer: 'Ольга М.',
      room: 'Бассейн',
      duration: '45 мин',
      spots: 4,
      total: 10,
      type: 'Бассейн',
      booked: false,
    },
    {
      id: 'class-boxing',
      date: '2026-04-21',
      time: '18:00',
      name: 'Бокс для начинающих',
      trainer: 'Антон П.',
      room: 'Зал №1',
      duration: '60 мин',
      spots: 1,
      total: 8,
      type: 'Бокс',
      booked: true,
    },
    {
      id: 'class-strength',
      date: '2026-04-22',
      time: '19:00',
      name: 'Силовая тренировка',
      trainer: 'Игорь В.',
      room: 'Зал №2',
      duration: '60 мин',
      spots: 0,
      total: 10,
      type: 'Групповые',
      booked: false,
    },
    {
      id: 'class-cycling',
      date: '2026-04-23',
      time: '19:30',
      name: 'Cycling',
      trainer: 'Денис Р.',
      room: 'Велозал',
      duration: '45 мин',
      spots: 3,
      total: 16,
      type: 'Групповые',
      booked: false,
    },
  ],

  visits: [
    { id: 'vis-01', clientId: 'client-anna', name: 'Анна Карпова', time: '09:12', zone: 'Тренажёрный зал', ok: true, status: '✓' },
    { id: 'vis-02', clientId: 'client-pavel', name: 'Павел Седов', time: '09:08', zone: 'Ресепшн', ok: true, status: '✓' },
    { id: 'vis-03', clientId: 'client-ilya', name: 'Илья Март', time: '09:05', zone: 'Ресепшн', ok: false, status: 'долг' },
    { id: 'vis-04', clientId: 'client-marina', name: 'Марина Жук', time: '08:52', zone: 'Групповые', ok: true, status: '✓' },
    { id: 'vis-05', clientId: 'client-diana', name: 'Диана Розова', time: '08:47', zone: 'Бассейн', ok: true, status: '✓' },
    { id: 'vis-06', clientId: 'client-oleg', name: 'Олег Трошин', time: '08:31', zone: 'Тренажёрный зал', ok: true, status: '✓' },
    { id: 'vis-07', clientId: 'client-anna', name: 'Анна Карпова', time: '07:55', zone: 'Сауна', ok: true, status: '✓' },
    { id: 'vis-08', clientId: 'client-kate', name: 'Екатерина Лесная', time: '07:40', zone: 'Ресепшн', ok: false, status: 'нет абонемента' },
  ],

  trainerClients: [
    {
      id: 'client-anna',
      name: 'Анна Карпова',
      initials: 'АК',
      phone: '+7 (999) 123-45-67',
      packageDone: 18,
      packageTotal: 24,
      status: 'active',
      age: 29,
      weight: 62,
      goal: 'похудение',
      nextSession: '23 апреля · 16:00',
    },
    {
      id: 'client-pavel',
      name: 'Павел Седов',
      initials: 'ПС',
      phone: '+7 (999) 234-56-78',
      packageDone: 12,
      packageTotal: 20,
      status: 'warn',
      age: 34,
      weight: 88,
      goal: 'снижение веса',
      nextSession: '22 апреля · 17:00',
    },
    {
      id: 'client-marina',
      name: 'Марина Жук',
      initials: 'МЖ',
      phone: '+7 (999) 345-67-89',
      packageDone: 9,
      packageTotal: 12,
      status: 'active',
      age: 27,
      weight: 58,
      goal: 'тонус',
      nextSession: '23 апреля · 11:00',
    },
    {
      id: 'client-diana',
      name: 'Диана Розова',
      initials: 'ДР',
      phone: '+7 (999) 456-78-90',
      packageDone: 21,
      packageTotal: 24,
      status: 'active',
      age: 31,
      weight: 65,
      goal: 'набор массы',
      nextSession: '23 апреля · 18:30',
    },
    {
      id: 'client-ilya',
      name: 'Илья Март',
      initials: 'ИМ',
      phone: '+7 (999) 567-89-01',
      packageDone: 24,
      packageTotal: 24,
      status: 'done',
      age: 36,
      weight: 79,
      goal: 'реабилитация',
      nextSession: 'нет записи',
    },
    {
      id: 'client-oleg',
      name: 'Олег Трошин',
      initials: 'ОТ',
      phone: '+7 (999) 678-90-12',
      packageDone: 15,
      packageTotal: 18,
      status: 'warn',
      age: 42,
      weight: 91,
      goal: 'сила',
      nextSession: '22 апреля · 19:00',
    },
    {
      id: 'client-kate',
      name: 'Екатерина Лесная',
      initials: 'ЕЛ',
      phone: '+7 (999) 789-01-23',
      packageDone: 5,
      packageTotal: 12,
      status: 'new',
      age: 24,
      weight: 54,
      goal: 'гибкость и растяжка',
      nextSession: '21 апреля · 10:30',
    },
  ],

  trainers: [
    { id: 'trainer-igor', name: 'Игорь Волков', initials: 'ИВ', spec: 'Functional · КМС', rate: '3 200 ₽/ч', rating: '4.9', clients: 24 },
    { id: 'trainer-olga', name: 'Ольга Михина', initials: 'ОМ', spec: 'Йога · Стретчинг', rate: '2 400 ₽/ч', rating: '4.8', clients: 18 },
    { id: 'trainer-denis', name: 'Денис Романов', initials: 'ДР', spec: 'Сайкл · Плавание', rate: '2 800 ₽/ч', rating: '4.7', clients: 12 },
    { id: 'trainer-anton', name: 'Антон Петров', initials: 'АП', spec: 'Бокс · ММА', rate: '3 000 ₽/ч', rating: '4.6', clients: 15 },
  ],

  halls: [
    { id: 'hall-1', name: 'Зал №1 · силовой', area: '320 м²', capacity: 40, open: true, loadPct: 78 },
    { id: 'hall-2', name: 'Зал №2 · функционал', area: '180 м²', capacity: 15, open: true, loadPct: 92 },
    { id: 'hall-pool', name: 'Бассейн 50 м', area: 'вода', capacity: 30, open: true, loadPct: 54 },
    { id: 'hall-yoga', name: 'Зал №3 · йога', area: '120 м²', capacity: 20, open: true, loadPct: 45 },
  ],

  shifts: [
    {
      id: 'shift-1',
      date: '2026-04-20',
      startTime: '08:00',
      endTime: '16:00',
      staffId: 'trainer-igor',
      staffName: 'Игорь Волков',
      role: 'trainer',
      station: 'Зал №2',
      status: 'done',
      payout: 12800,
      notes: 'Утренний блок групповых и персональных',
    },
    {
      id: 'shift-2',
      date: '2026-04-20',
      startTime: '10:00',
      endTime: '18:00',
      staffId: 'trainer-olga',
      staffName: 'Ольга Михина',
      role: 'trainer',
      station: 'Йога-студия',
      status: 'planned',
      payout: 10400,
      notes: 'Вечерние занятия и растяжка',
    },
    {
      id: 'shift-3',
      date: '2026-04-20',
      startTime: '09:00',
      endTime: '17:00',
      staffId: 'admin-1',
      staffName: 'Админ смены',
      role: 'admin',
      station: 'Ресепшн',
      status: 'done',
      payout: 9600,
      notes: 'Чек-ин, касса, новые заявки',
    },
    {
      id: 'shift-4',
      date: '2026-04-21',
      startTime: '12:00',
      endTime: '20:00',
      staffId: 'reception-1',
      staffName: 'Мария Крылова',
      role: 'reception',
      station: 'Ресепшн',
      status: 'planned',
      payout: 8800,
      notes: 'Приём гостей и работа с абонементами',
    },
  ],

  settings: [
    { key: 'backup_enabled', label: 'Резервная копия', value: true, note: 'Ежедневный дамп базы перед закрытием клуба' },
    { key: 'integrations_enabled', label: 'Интеграции', value: true, note: 'Связка с расписанием и CRM включена' },
    { key: 'api_enabled', label: 'API доступ', value: false, note: 'Внешний доступ к админскому API отключён' },
    { key: 'audit_enabled', label: 'Журнал действий', value: true, note: 'Фиксация изменений и служебных операций' },
  ],

  workoutPlans: [
    {
      id: 'plan-pavel',
      clientId: 'client-pavel',
      client: 'Павел Седов',
      goal: 'Снижение веса -8 кг',
      sessions: 16,
      done: 8,
      exercises: [
        { id: 'ex-pavel-1', planId: 'plan-pavel', name: 'Приседания со штангой', sets: '4x12', weight: '60 кг' },
        { id: 'ex-pavel-2', planId: 'plan-pavel', name: 'Тяга верхнего блока', sets: '3x15', weight: '50 кг' },
        { id: 'ex-pavel-3', planId: 'plan-pavel', name: 'Жим гантелей лёжа', sets: '4x10', weight: '16 кг' },
      ],
    },
    {
      id: 'plan-marina',
      clientId: 'client-marina',
      client: 'Марина Жук',
      goal: 'Тонус + гибкость',
      sessions: 12,
      done: 5,
      exercises: [
        { id: 'ex-marina-1', planId: 'plan-marina', name: 'Приседания с весом тела', sets: '3x20', weight: '—' },
        { id: 'ex-marina-2', planId: 'plan-marina', name: 'Выпады', sets: '3x16', weight: '—' },
        { id: 'ex-marina-3', planId: 'plan-marina', name: 'Стретчинг спины', sets: '2x60с', weight: '—' },
      ],
    },
    {
      id: 'plan-diana',
      clientId: 'client-diana',
      client: 'Диана Розова',
      goal: 'Набор мышечной массы +3 кг',
      sessions: 20,
      done: 10,
      exercises: [
        { id: 'ex-diana-1', planId: 'plan-diana', name: 'Жим штанги лёжа', sets: '4x8', weight: '30 кг' },
        { id: 'ex-diana-2', planId: 'plan-diana', name: 'Тяга штанги в наклоне', sets: '4x10', weight: '25 кг' },
        { id: 'ex-diana-3', planId: 'plan-diana', name: 'Подтягивания', sets: '3x6', weight: 'с поддержкой' },
      ],
    },
  ],

  progress: {
    weightPoints: [73.6, 73.2, 72.8, 72.4, 72.1, 71.8, 71.5, 71.3, 71.0, 70.8, 70.5, 70.2],
    measures: [
      { label: 'Грудь', val: '92 см', delta: '-2' },
      { label: 'Талия', val: '74 см', delta: '-4' },
      { label: 'Бёдра', val: '98 см', delta: '-1' },
      { label: 'Плечи', val: '96 см', delta: '+1' },
    ],
    lifts: [
      { name: 'Приседания', val: '70 кг', delta: '+10 кг', sessions: 24 },
      { name: 'Жим лёжа', val: '45 кг', delta: '+5 кг', sessions: 18 },
      { name: 'Становая тяга', val: '80 кг', delta: '+15 кг', sessions: 20 },
      { name: 'Тяга блока', val: '55 кг', delta: '+8 кг', sessions: 14 },
    ],
    history: [
      { date: '20 апр', time: '19:00', name: 'Functional с Игорем' },
      { date: '18 апр', time: '07:30', name: 'Бассейн · 4 дорожка' },
      { date: '16 апр', time: '20:30', name: 'Персоналка с Игорем' },
      { date: '15 апр', time: '12:00', name: 'Стретчинг' },
      { date: '13 апр', time: '10:00', name: 'Групповая йога' },
      { date: '11 апр', time: '18:00', name: 'Силовая тренировка' },
      { date: '09 апр', time: '09:00', name: 'Аквааэробика' },
      { date: '07 апр', time: '19:30', name: 'Cycling' },
    ],
    heatmap,
  },

  tariffs: [
    {
      id: 'tariff-month',
      label: 'Месяц',
      price: '7 900 ₽',
      sub: 'базовый · без бассейна',
      membershipTitle: 'Месячный абонемент',
    },
    {
      id: 'tariff-half-year',
      label: '6 месяцев',
      price: '39 000 ₽',
      sub: '-15% · с бассейном',
      badge: 'ВЫГОДА',
      membershipTitle: 'Полугодовой абонемент',
    },
    {
      id: 'tariff-year',
      label: 'Год',
      price: '69 900 ₽',
      sub: 'всё включено · 2 заморозки',
      membershipTitle: 'Годовой безлимит',
    },
  ],

  payments: [
    { id: 'payment-1', name: 'Анна Карпова', amount: 18000, method: 'Карта', date: '01.04.2026', tariff: 'Годовой' },
    { id: 'payment-2', name: 'Павел Седов', amount: 3500, method: 'Наличные', date: '28.03.2026', tariff: 'Месячный' },
    { id: 'payment-3', name: 'Марина Жук', amount: 9500, method: 'Карта', date: '15.03.2026', tariff: 'Полугодовой' },
    { id: 'payment-4', name: 'Илья Морозов', amount: 3500, method: 'Карта', date: '10.03.2026', tariff: 'Месячный' },
    { id: 'payment-5', name: 'Диана Орлова', amount: 18000, method: 'Перевод', date: '05.03.2026', tariff: 'Годовой' },
  ],

  chats: [
    {
      id: 'chat-pavel',
      clientId: 'client-pavel',
      name: 'Павел Седов',
      initials: 'ПС',
      phone: '+7 (999) 234-56-78',
      last: 'Игорь, привет! Хочу добавить ещё одну тренировку на этой неделе',
      time: '12:30',
      unread: 1,
    },
    {
      id: 'chat-anna',
      clientId: 'client-anna',
      name: 'Анна Карпова',
      initials: 'АК',
      phone: '+7 (999) 123-45-67',
      last: 'Спасибо! Завтра буду',
      time: '11:10',
      unread: 0,
    },
    {
      id: 'chat-marina',
      clientId: 'client-marina',
      name: 'Марина Жук',
      initials: 'МЖ',
      phone: '+7 (999) 345-67-89',
      last: 'Можно перенести на пятницу?',
      time: 'вчера',
      unread: 2,
    },
  ],

  messages: [
    { id: 'msg-p1', chatId: 'chat-pavel', from: 'client', text: 'Игорь, привет! Хочу добавить ещё одну тренировку на этой неделе', time: '12:30' },
    { id: 'msg-p2', chatId: 'chat-pavel', from: 'trainer', text: 'Привет, Павел! В пятницу в 17:00 свободно, подходит?', time: '12:32' },
    { id: 'msg-p3', chatId: 'chat-pavel', from: 'client', text: 'Да, отлично! Записывайте', time: '12:34' },
    { id: 'msg-p4', chatId: 'chat-pavel', from: 'trainer', text: 'Готово, записал на пятницу 23 апр, 17:00. Зал №2', time: '12:35' },
    { id: 'msg-a1', chatId: 'chat-anna', from: 'trainer', text: 'Анна, завтра тренировка в 16:00, не забудьте', time: '10:50' },
    { id: 'msg-a2', chatId: 'chat-anna', from: 'client', text: 'Помню! Жду с нетерпением', time: '11:05' },
    { id: 'msg-a3', chatId: 'chat-anna', from: 'client', text: 'Спасибо! Завтра буду', time: '11:10' },
    { id: 'msg-m1', chatId: 'chat-marina', from: 'client', text: 'Добрый день! Можно перенести занятие на пятницу?', time: 'вчера' },
    { id: 'msg-m2', chatId: 'chat-marina', from: 'trainer', text: 'Здравствуйте, Марина! В пятницу 25 апр есть 11:00 или 14:00', time: 'вчера' },
    { id: 'msg-m3', chatId: 'chat-marina', from: 'client', text: 'Можно перенести на пятницу?', time: 'вчера' },
  ],

  notifications: [
    { id: 'notif-1', userId: 'client-anna', role: 'client', kind: 'booking', title: 'Запись подтверждена', body: 'Вы записаны на Функциональный тренинг 21 апреля в 09:30. Зал №2.', createdAt: Date.now() - 3600000, readAt: null },
    { id: 'notif-2', userId: 'client-anna', role: 'client', kind: 'payment', title: 'Абонемент активен', body: 'Ваш годовой абонемент действует до 1 июня 2026. Осталось 73 дня.', createdAt: Date.now() - 86400000, readAt: Date.now() - 80000000 },
    { id: 'notif-3', userId: 'client-anna', role: 'client', kind: 'recommendation', title: 'Новые рекомендации', body: 'Система проанализировала ваш прогресс и подготовила персональные рекомендации по тренировкам.', createdAt: Date.now() - 7200000, readAt: null },
    { id: 'notif-4', userId: 'client-anna', role: 'trainer', kind: 'chat', title: 'Новое сообщение', body: 'Павел Дорохов: «Хочу добавить ещё одну тренировку на этой неделе»', createdAt: Date.now() - 1800000, readAt: null },
    { id: 'notif-5', userId: 'client-anna', role: 'admin', kind: 'system', title: 'Синхронизация с 1С', body: 'Последняя синхронизация выполнена успешно. Загружено 3 пользователя, 2 абонемента.', createdAt: Date.now() - 172800000, readAt: Date.now() - 170000000 },
  ],
};
